/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthOrgsImport } from './routes/_auth.orgs'
import { Route as AuthOrgsIndexImport } from './routes/_auth.orgs.index'
import { Route as AuthOrgsOrgIdImport } from './routes/_auth.orgs.$orgId'
import { Route as AuthOrgsOrgIdIndexImport } from './routes/_auth.orgs.$orgId.index'
import { Route as AuthOrgsOrgIdChatImport } from './routes/_auth.orgs.$orgId.chat'
import { Route as AuthOrgsOrgIdProjectsProjectIdImport } from './routes/_auth.orgs.$orgId.projects.$projectId'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthOrgsRoute = AuthOrgsImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AuthRoute,
} as any)

const AuthOrgsIndexRoute = AuthOrgsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgsRoute,
} as any)

const AuthOrgsOrgIdRoute = AuthOrgsOrgIdImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AuthOrgsRoute,
} as any)

const AuthOrgsOrgIdIndexRoute = AuthOrgsOrgIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)

const AuthOrgsOrgIdChatRoute = AuthOrgsOrgIdChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthOrgsOrgIdRoute,
} as any)

const AuthOrgsOrgIdProjectsProjectIdRoute =
  AuthOrgsOrgIdProjectsProjectIdImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthOrgsOrgIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/orgs': {
      id: '/_auth/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof AuthOrgsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/orgs/$orgId': {
      id: '/_auth/orgs/$orgId'
      path: '/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthOrgsOrgIdImport
      parentRoute: typeof AuthOrgsImport
    }
    '/_auth/orgs/': {
      id: '/_auth/orgs/'
      path: '/'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AuthOrgsIndexImport
      parentRoute: typeof AuthOrgsImport
    }
    '/_auth/orgs/$orgId/chat': {
      id: '/_auth/orgs/$orgId/chat'
      path: '/chat'
      fullPath: '/orgs/$orgId/chat'
      preLoaderRoute: typeof AuthOrgsOrgIdChatImport
      parentRoute: typeof AuthOrgsOrgIdImport
    }
    '/_auth/orgs/$orgId/': {
      id: '/_auth/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthOrgsOrgIdIndexImport
      parentRoute: typeof AuthOrgsOrgIdImport
    }
    '/_auth/orgs/$orgId/projects/$projectId': {
      id: '/_auth/orgs/$orgId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/orgs/$orgId/projects/$projectId'
      preLoaderRoute: typeof AuthOrgsOrgIdProjectsProjectIdImport
      parentRoute: typeof AuthOrgsOrgIdImport
    }
  }
}

// Create and export the route tree

interface AuthOrgsOrgIdRouteChildren {
  AuthOrgsOrgIdChatRoute: typeof AuthOrgsOrgIdChatRoute
  AuthOrgsOrgIdIndexRoute: typeof AuthOrgsOrgIdIndexRoute
  AuthOrgsOrgIdProjectsProjectIdRoute: typeof AuthOrgsOrgIdProjectsProjectIdRoute
}

const AuthOrgsOrgIdRouteChildren: AuthOrgsOrgIdRouteChildren = {
  AuthOrgsOrgIdChatRoute: AuthOrgsOrgIdChatRoute,
  AuthOrgsOrgIdIndexRoute: AuthOrgsOrgIdIndexRoute,
  AuthOrgsOrgIdProjectsProjectIdRoute: AuthOrgsOrgIdProjectsProjectIdRoute,
}

const AuthOrgsOrgIdRouteWithChildren = AuthOrgsOrgIdRoute._addFileChildren(
  AuthOrgsOrgIdRouteChildren,
)

interface AuthOrgsRouteChildren {
  AuthOrgsOrgIdRoute: typeof AuthOrgsOrgIdRouteWithChildren
  AuthOrgsIndexRoute: typeof AuthOrgsIndexRoute
}

const AuthOrgsRouteChildren: AuthOrgsRouteChildren = {
  AuthOrgsOrgIdRoute: AuthOrgsOrgIdRouteWithChildren,
  AuthOrgsIndexRoute: AuthOrgsIndexRoute,
}

const AuthOrgsRouteWithChildren = AuthOrgsRoute._addFileChildren(
  AuthOrgsRouteChildren,
)

interface AuthRouteChildren {
  AuthOrgsRoute: typeof AuthOrgsRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOrgsRoute: AuthOrgsRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/orgs': typeof AuthOrgsRouteWithChildren
  '/orgs/$orgId': typeof AuthOrgsOrgIdRouteWithChildren
  '/orgs/': typeof AuthOrgsIndexRoute
  '/orgs/$orgId/chat': typeof AuthOrgsOrgIdChatRoute
  '/orgs/$orgId/': typeof AuthOrgsOrgIdIndexRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthOrgsOrgIdProjectsProjectIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/orgs': typeof AuthOrgsIndexRoute
  '/orgs/$orgId/chat': typeof AuthOrgsOrgIdChatRoute
  '/orgs/$orgId': typeof AuthOrgsOrgIdIndexRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthOrgsOrgIdProjectsProjectIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/orgs': typeof AuthOrgsRouteWithChildren
  '/_auth/orgs/$orgId': typeof AuthOrgsOrgIdRouteWithChildren
  '/_auth/orgs/': typeof AuthOrgsIndexRoute
  '/_auth/orgs/$orgId/chat': typeof AuthOrgsOrgIdChatRoute
  '/_auth/orgs/$orgId/': typeof AuthOrgsOrgIdIndexRoute
  '/_auth/orgs/$orgId/projects/$projectId': typeof AuthOrgsOrgIdProjectsProjectIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/orgs'
    | '/orgs/$orgId'
    | '/orgs/'
    | '/orgs/$orgId/chat'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/orgs'
    | '/orgs/$orgId/chat'
    | '/orgs/$orgId'
    | '/orgs/$orgId/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/orgs'
    | '/_auth/orgs/$orgId'
    | '/_auth/orgs/'
    | '/_auth/orgs/$orgId/chat'
    | '/_auth/orgs/$orgId/'
    | '/_auth/orgs/$orgId/projects/$projectId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/orgs"
      ]
    },
    "/_auth/orgs": {
      "filePath": "_auth.orgs.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/orgs/$orgId",
        "/_auth/orgs/"
      ]
    },
    "/_auth/orgs/$orgId": {
      "filePath": "_auth.orgs.$orgId.tsx",
      "parent": "/_auth/orgs",
      "children": [
        "/_auth/orgs/$orgId/chat",
        "/_auth/orgs/$orgId/",
        "/_auth/orgs/$orgId/projects/$projectId"
      ]
    },
    "/_auth/orgs/": {
      "filePath": "_auth.orgs.index.tsx",
      "parent": "/_auth/orgs"
    },
    "/_auth/orgs/$orgId/chat": {
      "filePath": "_auth.orgs.$orgId.chat.tsx",
      "parent": "/_auth/orgs/$orgId"
    },
    "/_auth/orgs/$orgId/": {
      "filePath": "_auth.orgs.$orgId.index.tsx",
      "parent": "/_auth/orgs/$orgId"
    },
    "/_auth/orgs/$orgId/projects/$projectId": {
      "filePath": "_auth.orgs.$orgId.projects.$projectId.tsx",
      "parent": "/_auth/orgs/$orgId"
    }
  }
}
ROUTE_MANIFEST_END */
