import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { HybridAgentFactory } from '../../agents/agent-factory-hybrid.js';

/**
 * Agent Invoker Service
 *
 * This service invokes project-specific agents that were generated by initialize-project.
 * These agents are located in {projectPath}/.claude/agents/ and include:
 * - planner.md (Opus) - Creates implementation plans
 * - implementer-{language}.md (Sonnet) - Language-specific implementers
 * - implementer-generic.md (Sonnet) - Generic implementer for any file type
 * - visual-verifier.md (Opus) - Visual regression testing
 *
 * Key difference from initialize-project agents:
 * - initialize-project uses framework agents from {frameworkPath}/orchestration/agents/
 * - implement-ticket uses generated agents from {projectPath}/.claude/agents/
 */

export interface ProjectAgentConfig {
  agentName: string;
  agentFile: string;
  projectPath: string;
  frameworkPath: string;
  additionalContext?: string;
  timeout?: number;
}

export interface AgentInvokeResult {
  output: string;
  mode: 'api_key' | 'claude_cli';
  executionTimeMs: number;
}

/**
 * Service for invoking project-specific agents generated by initialize-project
 */
export class AgentInvokerService {
  private projectPath: string;
  private frameworkPath: string;

  constructor(projectPath: string, frameworkPath: string) {
    this.projectPath = projectPath;
    this.frameworkPath = frameworkPath;
  }

  /**
   * Invoke a project-specific agent
   *
   * @param agentName - Agent name (e.g., 'planner', 'implementer-typescript')
   * @param agentFile - Agent filename (e.g., 'planner.md')
   * @param input - Input prompt for the agent
   * @param additionalContext - Optional additional context to prepend to agent instructions
   * @param timeout - Optional timeout in milliseconds (default: 600000 = 10 minutes)
   * @returns Agent output
   */
  async invokeAgent(
    agentName: string,
    agentFile: string,
    input: string,
    additionalContext?: string,
    timeout: number = 600000
  ): Promise<AgentInvokeResult> {
    // Validate agent file exists
    const agentPath = join(this.projectPath, '.claude', 'agents', agentFile);

    if (!existsSync(agentPath)) {
      throw new Error(
        `Agent file not found: ${agentPath}\n` +
        `Make sure initialize-project has been run to generate agents.`
      );
    }

    // Read agent instructions
    const agentInstructions = readFileSync(agentPath, 'utf-8');

    // Build full prompt
    const fullPrompt = this.buildAgentPrompt(
      agentInstructions,
      input,
      additionalContext
    );

    // Create hybrid agent factory
    const factory = await HybridAgentFactory.create();

    // Create agent using hybrid factory
    // Note: For project agents, we need a custom config since HybridAgentFactory
    // looks in {frameworkPath}/.claude/agents/ by default
    // We'll use additionalContext to pass the full prompt and bypass file reading
    const hybridAgent = await factory.createAgent({
      agentName,
      agentFile: agentFile, // This won't be used since we're passing additionalContext
      projectPath: this.projectPath,
      frameworkPath: this.frameworkPath,
      additionalContext: fullPrompt,
      timeout
    });

    // Invoke agent
    const result = await hybridAgent.invoke({ input });

    // Log execution info
    console.log(
      `[${agentName}] Completed in ${result.executionTimeMs}ms using ${result.mode} mode`
    );

    return {
      output: result.output,
      mode: result.mode as 'api_key' | 'claude_cli',
      executionTimeMs: result.executionTimeMs
    };
  }

  /**
   * Build the full prompt for an agent
   *
   * @param agentInstructions - Markdown instructions from agent file
   * @param input - User input/task
   * @param additionalContext - Optional additional context
   * @returns Full prompt string
   */
  private buildAgentPrompt(
    agentInstructions: string,
    input: string,
    additionalContext?: string
  ): string {
    const lines: string[] = [];

    // Add agent instructions
    lines.push(agentInstructions);
    lines.push('');

    // Add additional context if provided
    if (additionalContext) {
      lines.push('=== ADDITIONAL CONTEXT ===');
      lines.push(additionalContext);
      lines.push('');
    }

    // Add user input
    lines.push('=== TASK ===');
    lines.push(input);

    return lines.join('\n');
  }

  /**
   * Invoke the planner agent (Opus)
   *
   * @param context - Implementation context from Phase 1
   * @param stackProfile - Stack profile from Phase 0
   * @param ticketId - Ticket ID
   * @returns Implementation plan (markdown)
   */
  async invokePlanner(
    context: string,
    stackProfile: any,
    ticketId: string
  ): Promise<string> {
    const input = `
Create a detailed implementation plan for ticket ${ticketId}.

## Context

${context}

## Stack Profile

**Primary Language**: ${stackProfile.primary_language || 'Unknown'}
**Languages**: ${(stackProfile.languages || []).join(', ') || 'None'}
**Frameworks**:
  - Frontend: ${(stackProfile.frameworks?.frontend || []).join(', ') || 'None'}
  - Backend: ${(stackProfile.frameworks?.backend || []).join(', ') || 'None'}
**Testing**: ${Object.keys(stackProfile.testing_frameworks || {}).join(', ') || 'Unknown'}

## Requirements

Create a comprehensive implementation plan that includes:

1. **Implementation Steps**: Detailed step-by-step implementation instructions
2. **Test Plan**: Unit, integration, and E2E test requirements
3. **Environment Requirements**: Any Docker, services, or env vars needed
4. **Risk Assessment**: Potential risks and mitigation strategies

Output the plan in markdown format with clear sections.
    `.trim();

    const result = await this.invokeAgent(
      'planner',
      'planner.md',
      input
    );

    return result.output;
  }

  /**
   * Invoke language-specific implementer agent (Sonnet)
   *
   * @param language - Primary language (e.g., 'typescript', 'python')
   * @param plan - Implementation plan from planner
   * @param context - Full context
   * @param useGenericImplementer - Whether to fall back to generic implementer
   * @returns Implementation output
   */
  async invokeImplementer(
    language: string,
    plan: string,
    context: string,
    useGenericImplementer: boolean = false
  ): Promise<string> {
    const agentFile = useGenericImplementer
      ? 'implementer-generic.md'
      : `implementer-${language}.md`;

    const agentName = useGenericImplementer
      ? 'implementer-generic'
      : `implementer-${language}`;

    // Check if language-specific implementer exists
    const agentPath = join(this.projectPath, '.claude', 'agents', agentFile);

    if (!existsSync(agentPath)) {
      if (useGenericImplementer) {
        throw new Error(
          `Generic implementer not found at ${agentPath}. ` +
          `This should have been generated by initialize-project.`
        );
      }

      // Fall back to generic implementer
      console.log(
        `[AgentInvoker] Language-specific implementer not found: ${agentFile}`
      );
      console.log(`[AgentInvoker] Falling back to generic implementer`);

      return this.invokeImplementer(language, plan, context, true);
    }

    const input = `
Implement the changes according to the plan below.

## Implementation Plan

${plan}

## Context

${context}

## Instructions

Follow the plan exactly. Make the necessary code changes to implement the required functionality.
Ensure all code follows the team's conventions and patterns outlined in the project-context skill.
    `.trim();

    const result = await this.invokeAgent(
      agentName,
      agentFile,
      input
    );

    return result.output;
  }

  /**
   * Invoke visual verifier agent (Opus) - only if frontend frameworks detected
   *
   * @param screenshotsBefore - Paths to before screenshots
   * @param screenshotsAfter - Paths to after screenshots
   * @param diffReport - Diff report from screenshot comparison
   * @param dualModeOptions - Optional dual-mode visual testing params
   * @returns Visual verification verdict
   */
  async invokeVisualVerifier(
    screenshotsBefore: string[],
    screenshotsAfter: string[],
    diffReport: any,
    dualModeOptions?: {
      mode?: 'figma' | 'screenshot' | 'both';
      figmaImagesPath?: string;
      figmaConstraints?: string;
      diffThreshold?: number;
      expectedImages?: string[];
      actualImages?: string[];
    }
  ): Promise<string> {
    const mode = dualModeOptions?.mode ?? 'screenshot';
    const threshold = dualModeOptions?.diffThreshold ?? 5;

    let input = `
Analyze the visual changes between before and after screenshots.

## Visual Mode
${mode}

## Diff Threshold
${threshold}%

## Screenshots Before / Expected
${(dualModeOptions?.expectedImages ?? screenshotsBefore).join('\n')}

## Screenshots After / Actual
${(dualModeOptions?.actualImages ?? screenshotsAfter).join('\n')}

## Diff Report
${JSON.stringify(diffReport, null, 2)}
`.trim();

    if (dualModeOptions?.figmaConstraints) {
      input += `\n\n## Figma Constraints\n${dualModeOptions.figmaConstraints}`;
    }

    if (dualModeOptions?.figmaImagesPath) {
      input += `\n\n## Figma Images Path\n${dualModeOptions.figmaImagesPath}`;
    }

    input += `

## Instructions

1. Review all visual changes
2. Identify any regressions or unexpected changes
3. Provide a verdict: PASS or FAIL
4. List specific issues if FAIL
5. Suggest fixes if needed
${mode === 'figma' || mode === 'both' ? '6. Cross-reference diffs with Figma constraints for design fidelity issues' : ''}
`;

    const agentPath = join(this.projectPath, '.claude', 'agents', 'visual-verifier.md');

    if (!existsSync(agentPath)) {
      console.log('[AgentInvoker] Visual verifier not found (frontend frameworks not detected)');
      return 'SKIP: No visual verifier available (frontend frameworks not detected)';
    }

    const result = await this.invokeAgent(
      'visual-verifier',
      'visual-verifier.md',
      input
    );

    return result.output;
  }
}
