/**
 * Deterministic renderer for the `docs/llm-wiki/wiki/getting-started.md` page.
 *
 * Pure function. Builds the wiki page from the `command_catalog` plus verbatim
 * README "Getting Started" extracts. No LLM, no editorial decisions — operators
 * see exactly what the analyzer captured.
 */

import type {
  CommandCatalog,
  CommandCatalogEntry,
  CommandCatalogOperation,
  ReadmeRunSectionEntry,
} from '../../../schemas/stack-profile.schema.js';

export interface GettingStartedRendererInput {
  projectName: string;
  commandCatalog: CommandCatalog;
  readmeRunSections?: ReadmeRunSectionEntry[];
}

const OPERATION_ORDER: CommandCatalogOperation[] = [
  'setup',
  'start_dev',
  'run_tests',
  'run_unit_tests',
  'run_integration_tests',
  'run_e2e',
  'run_build',
  'run_lint',
  'run_format',
  'run_typecheck',
  'run_migrations',
  'generate_migration',
  'revert_migration',
  'seed',
  'reset',
];

const OPERATION_LABEL: Record<CommandCatalogOperation, string> = {
  setup: 'Setup',
  start_dev: 'Start dev server',
  run_tests: 'Run tests',
  run_unit_tests: 'Run unit tests',
  run_integration_tests: 'Run integration tests',
  run_e2e: 'Run end-to-end tests',
  run_build: 'Build',
  run_lint: 'Lint',
  run_format: 'Format',
  run_typecheck: 'Typecheck',
  run_migrations: 'Run database migrations',
  generate_migration: 'Generate migration',
  revert_migration: 'Revert migration',
  seed: 'Seed database',
  reset: 'Reset environment',
};

/**
 * Render `getting-started.md` deterministically.
 *
 * Page structure:
 *   1. Title + one-line note about source-of-truth.
 *   2. README "Getting Started" block — verbatim, blockquoted, with
 *      attribution.
 *   3. Wrapper-tier table — `make`/`just`/`task`/scripts entries
 *      with descriptions extracted from the source file.
 *   4. Per-service commands subtable — package-manager fallbacks
 *      with the warning sentence.
 *   5. CI hints (only if present, only when no wrapper/package-mgr
 *      candidates surfaced for an op).
 */
export function renderGettingStarted(input: GettingStartedRendererInput): string {
  const { projectName, commandCatalog, readmeRunSections } = input;

  const sections: string[] = [];
  sections.push(`# Getting started — ${projectName}`);
  sections.push('');
  sections.push(
    '_Generated by the AI Agentic Framework. Source-of-truth for "how to run this project" — ' +
      'derived from your `Makefile` / `Justfile` / `Taskfile` / setup scripts (Tier 1), ' +
      'README "Getting Started" sections (Tier 2), per-service package-manager scripts ' +
      '(Tier 3), and CI hints (Tier 4)._',
  );
  sections.push('');

  if (readmeRunSections && readmeRunSections.length > 0) {
    sections.push(...renderReadmeSections(readmeRunSections));
  }

  const wrapperRows = collectRows(commandCatalog, 'wrapper');
  if (wrapperRows.length > 0) {
    sections.push('## Wrapper commands');
    sections.push('');
    sections.push(
      'These wrappers are the canonical entry points. They ' +
        'orchestrate dependent services (databases, queues, auth ' +
        "providers, etc.) and apply the project's setup invariants.",
    );
    sections.push('');
    sections.push('| Action | Command | Description | Source |');
    sections.push('|---|---|---|---|');
    for (const r of wrapperRows) {
      sections.push(
        `| ${OPERATION_LABEL[r.op]} | \`${r.entry.command}\` | ${escapeCell(r.entry.description ?? '—')} | \`${r.entry.source}\` |`,
      );
    }
    sections.push('');
  }

  const pmRows = collectRows(commandCatalog, 'package_manager');
  if (pmRows.length > 0) {
    sections.push('## Per-service commands (low-level)');
    sections.push('');
    sections.push(
      '> **Prefer the wrapper above when present; these run a single ' +
        'service in isolation and may not start dependent services ' +
        '(databases, queues, identity providers).** Use them when you ' +
        'need to iterate on a single service inside an already-running ' +
        'wrapper-managed environment.',
    );
    sections.push('');
    sections.push('| Action | Service | Command | Source |');
    sections.push('|---|---|---|---|');
    for (const r of pmRows) {
      sections.push(
        `| ${OPERATION_LABEL[r.op]} | \`${r.entry.per_service ?? '—'}\` | \`${r.entry.command}\` | \`${r.entry.source}\` |`,
      );
    }
    sections.push('');
  }

  const ciRows = collectRows(commandCatalog, 'ci');
  const ciOpsCovered = new Set([...wrapperRows, ...pmRows].map((r) => r.op));
  const orphanCiRows = ciRows.filter((r) => !ciOpsCovered.has(r.op));
  if (orphanCiRows.length > 0) {
    sections.push('## CI-derived hints (last-resort)');
    sections.push('');
    sections.push(
      '_Extracted from CI workflow definitions. No wrapper or per-service ' +
        'script was discovered for these operations; CI is the only ' +
        'documentation we have._',
    );
    sections.push('');
    sections.push('| Action | Command | Source |');
    sections.push('|---|---|---|');
    for (const r of orphanCiRows) {
      sections.push(
        `| ${OPERATION_LABEL[r.op]} | \`${r.entry.command}\` | \`${r.entry.source}\` |`,
      );
    }
    sections.push('');
  }

  if (wrapperRows.length === 0 && pmRows.length === 0 && orphanCiRows.length === 0) {
    sections.push('## (No commands discovered)');
    sections.push('');
    sections.push(
      'Phase 1 analyzers found no Makefile / Justfile / Taskfile / setup ' +
        'script / package-manager scripts / CI commands in this project. ' +
        'Add a wrapper (`Makefile` with documented targets) or a README ' +
        '"Getting Started" section, then re-run `/initialize-project`.',
    );
    sections.push('');
  }

  return sections.join('\n');
}

function collectRows(
  catalog: CommandCatalog,
  tier: CommandCatalogEntry['tier'],
): Array<{ op: CommandCatalogOperation; entry: CommandCatalogEntry }> {
  const rows: Array<{ op: CommandCatalogOperation; entry: CommandCatalogEntry }> = [];
  for (const op of OPERATION_ORDER) {
    const entries = catalog[op];
    if (!entries) continue;
    for (const e of entries) {
      if (e.tier === tier) rows.push({ op, entry: e });
    }
  }
  return rows;
}

function renderReadmeSections(sections: ReadmeRunSectionEntry[]): string[] {
  const out: string[] = [];
  out.push('## From the project README');
  out.push('');
  out.push(
    '_Reproduced verbatim from the README — the original wording is ' +
      'authoritative for any quirks the wrapper / package-manager tables ' +
      'below may miss._',
  );
  out.push('');
  for (const s of sections) {
    out.push(`### ${s.heading}`);
    out.push('');
    out.push(`_Source: \`${s.path}\` § ${s.heading}_`);
    out.push('');
    for (const line of s.body.split('\n')) {
      out.push(line.length > 0 ? `> ${line}` : '>');
    }
    out.push('');
  }
  return out;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n+/g, ' ');
}
